### ISSUE TITLE
What is the best way to go about badging?

### ISSUE THREAD

**Issue by bryan1anderson** [zijievv/swiftui-tab-bar#2]
Would you load the icon and text into a Stack and then put a badge over that?

**Comment by zijievv** [comment]
In fact, the tab item label has already been placed within a `VStack`. The tab item label accepts any `ViewBuilder`, and if users provide different item labels with different heights, the badges will be uneven. So, I haven't figured out how to add badges yet. Currently, it's not a difficult task even if users add badges themselves. I might consider adding this feature later on.
