### ISSUE TITLE
State change

### ISSUE THREAD

**Issue by fatihdurmaz** [zijievv/swiftui-tab-bar#3]
When selecting from the tab bar, the states of the views are not preserved. how can i prevent this state

https://github.com/zijievv/swiftui-tab-bar/assets/71706970/a15c9c93-5868-420f-a681-31d2c1d23314

**Comment by zijievv** [comment]
@fatihdurmaz Which version of the package are you using? Only 0.2.3 and later can preserve the state when switching tabs.

**Comment by fatihdurmaz** [comment]
Updating package  solved problem thnks
