### ISSUE TITLE
Tab bar is hidden even when keyboard is not presented but when iPadOS is presenting the minimized text entry bubble

### ISSUE THREAD

**Issue by bryan1anderson** [zijievv/swiftui-tab-bar#7]
<img width="508" alt="Screenshot 2023-08-31 at 1 58 09 PM" src="https://github.com/zijievv/swiftui-tab-bar/assets/7976521/ff947798-50b6-484f-b0a4-cb5c50bfc147">

Something tells me hiding this thing when when keyboard is active isn't necessarily the best way to accomplish this

**Comment by zijievv** [comment]
By default, the tab bar will automatically show/hide. You can pass in a Binding value of `Visibility` to show/hide the tab bar according to your own needs.
