### ISSUE TITLE
SubView hide

### ISSUE THREAD

**Issue by fatihdurmaz** [zijievv/swiftui-tab-bar#9]
![Simulator Screen Recording - iPhone 15 Plus - 2023-11-03 at 15 46 02](https://github.com/zijievv/swiftui-tab-bar/assets/71706970/e59e2311-114d-4af1-9253-a03c411d563a)
How can I hide the tabbar when directed to the subview with NavigationStack?

{
        NavigationStack {
            PagerTabStripView(selection: $selectedPageItem) {
                NowPlayingMovieGridView(numberOfColumns: $numberOfColumns)
                    .pagerTabItem(tag: 1) {
                        PageItem(title: "Now Playing")
                            .font(.system(.footnote, design: .rounded).weight(selectedPageItem == 1 ? .bold : .medium))
                    }
                PopularMovieGridView(numberOfColumns: $numberOfColumns)
                    .pagerTabItem(tag: 2) {
                        PageItem(title: "Popular")
                            .font(.system(.footnote).weight(selectedPageItem == 2 ? .bold : .medium))
                    }
                TopRatedMovieGridView(numberOfColumns: $numberOfColumns)
                    .pagerTabItem(tag: 3) {
                        PageItem(title: "Top Rated")
                            .font(.system(.footnote, design: .rounded).weight(selectedPageItem == 3 ? .bold : .medium))
                    }
            }
            .navigationTitle("Movies")
            .toolbar{
                ToolbarItem{
                    Picker("Column Count", selection: $numberOfColumns.animation(.default)) {
                        Text("2").tag(2)
                        Text("3").tag(3)
                        Text("4").tag(4)
                    }
                    .pickerStyle(.segmented)
                    .frame(width: 150)
                }
            }
        }
        .tint(.black)
    }

**Comment by fatihdurmaz** [comment]
![Uploading Simulator Screen Recording - iPhone 15 Plus - 2023-11-03 at 15.46.02.gif…]()

**Comment by fatihdurmaz** [comment]
var body: some View {
        VStack {
            GeometryReader { geometry in
                ScrollView {
                    LazyVGrid(columns: columns, spacing:20) {
                        ForEach(viewModel.movies) { movie in
                            NavigationLink(destination: MovieDetailView(movie: movie)) {
                                SDWebImageView(url: movie.posterURL)
                                    .frame(width: (geometry.size.width - CGFloat(numberOfColumns) * 10) / CGFloat(numberOfColumns))
                                    .onAppear {
                                        if movie.id == viewModel.movies.last?.id {
                                            currentPage += 1
                                            viewModel.fetchMovies(page: currentPage)
                                        }
                                    }
                            }
                        }
                    }
                    .padding(.bottom, 65)
                }
                .onAppear{
                    viewModel.fetchMovies(page: currentPage)
                }
            }
        }
        .padding(.top)
    }
}

**Comment by zijievv** [comment]
You can pass a binding value of type `Visibility` to the `TabBar`.

```swift
@State var selection: Int = 0
@State var visibility: Visibility = .visible

TabBar(selection: $selection, visibility: $visibility) {
    // Content
}
```

And change the visibility whenever necessary.

**Comment by fatihdurmaz** [comment]
I need to define this in each subview. Could there be a simpler solution?
